export const mockSearchResponse = {
  query: '',
  results: [
    {
      url: 'https://privacydesign.org/future',
      title: 'The Future of Privacy Design',
      content: 'Exploring how intent-driven systems represent the next leap in user privacy, discarding traditional tracking models.',
      engine: 'editorial',
      original_score: 0.82,
      ranked_score: 0.89,
      rank: 1,
      category: 'general',
      intent_goal: 'FIND_INFORMATION',
      match_reasons: ['High relevance', 'Privacy focused'],
      privacy_score: 0.95,
      ethical_alignment: 0.92,
      tags: ['Privacy', 'Design'],
    },
    {
      url: 'https://designweekly.com/organic-aesthetics',
      title: 'Organic Aesthetics in Modern Web',
      content: 'A deep dive into why generic AI layouts are being replaced by tailored, highly-crafted editorial layouts.',
      engine: 'searxng',
      original_score: 0.71,
      ranked_score: 0.75,
      rank: 2,
      category: 'general',
      intent_goal: 'LEARN',
      match_reasons: ['Topic match', 'Quality source'],
      privacy_score: 0.88,
      ethical_alignment: 0.85,
      tags: ['Aesthetics', 'Frontend'],
    },
    {
      url: 'https://techjournal.io/intent-engine-arch',
      title: 'Intent Engine Architecture',
      content: 'Understanding the constraint satisfaction and ranking mechanisms behind the new search paradigm.',
      engine: 'vector',
      original_score: 0.88,
      ranked_score: 0.92,
      rank: 3,
      category: 'general',
      intent_goal: 'LEARN',
      match_reasons: ['Direct match', 'Authoritative'],
      privacy_score: 0.91,
      ethical_alignment: 0.90,
      tags: ['Engineering', 'Architecture'],
    },
  ],
  total_results: 3,
  processing_time_ms: 142.5,
  extracted_intent: {
    goal: 'FIND_INFORMATION',
    constraints: [{ type: 'topic', value: 'intent-driven search' }],
    use_cases: ['LEARNING', 'VERIFICATION'],
    result_type: 'article',
    complexity: 'moderate',
    confidence: 0.87,
  },
  engines_used: ['searxng', 'vector', 'editorial'],
  categories_searched: ['general'],
  ranking_applied: true,
  results_ranked: 3,
  privacy_enhanced: true,
  tracking_blocked: true,
};

export const mockConsentSummary = {
  timestamp: new Date().toISOString(),
  total_consents: 1284,
  granted_consents: 1103,
  denied_consents: 181,
  by_type: {
    analytics: 402,
    advertising: 287,
    functional: 412,
    essential: 183,
  },
  overall_compliance_rate: 85.9,
};

export const mockAuditStats = {
  timestamp: new Date().toISOString(),
  total_events: 4521,
  events_by_type: {
    consent_granted: 1103,
    consent_denied: 181,
    data_access: 892,
    data_deletion: 67,
    policy_update: 34,
    privacy_check: 2244,
  },
  daily_counts: [
    { date: '2026-03-31', count: 612 },
    { date: '2026-04-01', count: 580 },
    { date: '2026-04-02', count: 701 },
    { date: '2026-04-03', count: 654 },
    { date: '2026-04-04', count: 738 },
    { date: '2026-04-05', count: 590 },
    { date: '2026-04-06', count: 646 },
  ],
  recent_activity: 646,
};

export const mockCampaignPerformance = [
  {
    campaign_id: 1,
    campaign_name: 'Spring Privacy Campaign',
    impressions: 24500,
    clicks: 1830,
    conversions: 142,
    ctr: 7.47,
    cpc: 0.82,
    cost: 1500.6,
    roas: 3.2,
  },
  {
    campaign_id: 2,
    campaign_name: 'Developer Tools Launch',
    impressions: 18200,
    clicks: 1456,
    conversions: 98,
    ctr: 8.0,
    cpc: 0.65,
    cost: 946.4,
    roas: 4.1,
  },
  {
    campaign_id: 3,
    campaign_name: 'Ethical Search Awareness',
    impressions: 31000,
    clicks: 2108,
    conversions: 187,
    ctr: 6.8,
    cpc: 0.71,
    cost: 1496.68,
    roas: 3.8,
  },
];

export const mockLiveMetrics = {
  timestamp: new Date().toISOString(),
  impressions: 73700,
  clicks: 5394,
  conversions: 427,
  ctr: 7.32,
  cpc: 0.73,
  roas: 3.7,
  active_campaigns: 3,
  live_users: 284,
};
